routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'StaticController@homePage')->name('home-page');
Route::get('/registro', 'StaticController@registro')->name('registro');
Route::get('/fin', 'StaticController@posRegistro')->name('fin');

Route::resource('participantes', 'ParticipantController');


Route::prefix('4dm1n')->group(function() {
  Auth::routes();
  Route::get('home', 'HomeController@index')->name('home');
  Route::get('reportes', 'HomeController@export')->name('reports');

});

app/Models/Participant.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Participant extends Model
{
    //
    protected $guarded = [];
    
}

app/Models/User.php
<?php

namespace App\Models;


use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Participant;

USE App\Exports\ParticipatsExport;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $participants = Participant::orderBy('id', 'ASC')->paginate(8);
        return view('home',compact("participants"));
    }

    public function export(ParticipatsExport $participant)
    {
        return  $participant->download('participantes.xlsx');
    }
}

app/Http/Controllers/ParticipantController.php
<?php

namespace App\Http\Controllers;

use App\Models\Participant;
use App\Http\Requests\ParticipantStoreRequest;
use Illuminate\Http\Request;

class ParticipantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\ParticipantStoreRequest  $request
     * @return $atttributes
     */

    public function store(ParticipantStoreRequest $request)
    {
        $participant = Participant::create( $request->all() );

        // sube las imagenes y las guarda en la base
        if ($request->hasFile('imgFront')){
          $name = $participant->dni."-Frontal.". $request->imgFront->extension();
          $participant->imgFront = $request->file('imgFront')->storeAs('public/'.$participant->id, $name);
        }

        if ($request->hasFile('imgBack')){
          $nameback = $participant->dni."-Trasera.". $request->imgBack->extension();
          $participant->imgBack = $request->file('imgBack')->storeAs('public/'.$participant->id, $nameback);
        }

        $participant->save();

        return redirect()->route('registro')->with('message','Sus datos han sido guardados.');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Participant  $participant
     * @return \Illuminate\Http\Response
     */
    public function show(Participant $participant)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Participant  $participant
     * @return \Illuminate\Http\Response
     */
    public function edit(Participant $participant)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Participant  $participant
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Participant $participant)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Participant  $participant
     * @return \Illuminate\Http\Response
     */
    public function destroy(Participant $participant)
    {
        //
    }
}

app/Http/Controllers/StaticController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Participant;

class StaticController extends Controller
{
    //
    public function homePage()
    {
        if(\CompareDate::CompareHigh("01-03-2019 12:00:00"))
          return redirect()->route('registro');

        $pre = true;
        return view('preRegistry.index', compact("pre"));
    }

    public function registro()
    {

      if(\CompareDate::CompareLess("01-03-2019 12:00:00"))
          return redirect()->route('home-page');

      if(\CompareDate::CompareHigh("04-03-2019 23:59:00"))
        return redirect()->route('fin');

      $pre = false;
      return view('registry.index', compact("pre"));
    }

    public function posRegistro()
    {
      if(\CompareDate::CompareLess("01-03-2019 23:59:00"))
          return redirect()->route('registro');

      $pre = false;

      return view('posRegistry.index', compact("pre"));

    }

}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<<<<<<< HEAD
<div class="container-fluid">
=======
<div class="container">
>>>>>>> 25d45d34b38ff911b9ef406bbbf9d50718f2d0fd
    <div class="row justify-content-center">
      <div class="table-responsive">
        <a href="{{ route('reports')}}"  class="btn btn-info">Descargar reporte</a>
        {!! $participants->Render() !!}
        <table class="table table-striped">
          <thead class="thead-dark">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Nombre</th>
              <th scope="col">Apellidos</th>
              <th scope="col">Email</th>
              <th scope="col">DNI</th>
              <th scope="col">Teléfono</th>
              <th scope="col">Imagen Frontal</th>
              <th scope="col">Imagen Trasera</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($participants as $key => $participant)
              <tr>
                <td scope="row">{{ $participant->id }}</td>
                <td>{{ $participant->name }}</td>
                <td>{{ $participant->apellidos }}</td>
                <td>{{ $participant->email }}</td>
                <td>{{ $participant->dni }}</td>
                <td>{{ $participant->phone }}</td>
                <td> <img class="imgTable" src="{{ Storage::url( $participant->imgFront ) }}" alt="{{ $participant->name }}"></td>
                <td> <img class="imgTable" src="{{ Storage::url( $participant->imgBack ) }}" alt="{{ $participant->name }}"></td>
              </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/login.css') }}" rel="stylesheet">

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/4dm1n/home') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            {{-- <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif --}}
                        @else
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    {{-- Google tag manager --}}
    {{-- @include("snippets.analytics") --}}
    @php
      header("Expires: Tue, 01 Jul 2001 06:00:00 GMT");
      header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
      header("Cache-Control: no-store, no-cache, must-revalidate");
      header("Cache-Control: post-check=0, pre-check=0", false);
      header("Pragma: no-cache");
    @endphp
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>4 Latas</title>
    {{-- metatags --}}
    @include("snippets.metatags")
    {{-- favicons --}}
    @include("snippets.favicons")
    {{-- stylesheets --}}
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    @include("shared._preloader")

    {{-- content --}}
    <div id="main-wrapper">
          @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/posRegistry/index.blade.php
@extends('layouts.default')
@section('content')
  <div class="container text-center" id="posRegistry">

    @include('shared._header')

    <div class="col-md-12 contenido">
      <h2>¡Gracias por participar!</h2>
      <h1>EL REGISTRO HA CERRADO</h1>
      <p>Pronto anunciaremos a los ganadores</p>
      <a href="{{ asset('terminos_condiciones/terminos.pdf') }}" target="_blank">Términos y condiciones</a>
      <p><img src="{{ asset('images/4latas-carro2.png') }}" alt=""></p>
    </div>


  </div>


@endsection

resources/views/preRegistry/index.blade.php
@extends('layouts.default')
@section('content')
  <div class="container text-center" id="preRegistry">
    @include('shared._header')
    @include('shared._date')

    <div id="footer" class="col-md-12">
      <p>Necesitarás:</p>
      <p>Foto de tu entrada para ver 4 Latas (a dos caras)</p>
      <a href="{{ asset('terminos_condiciones/terminos.pdf') }}" target="_blank">Términos y condiciones</a>
      <p><img src="{{ asset('images/4latas-carro2.png') }}" alt=""></p>
    </div>


  </div>


@endsection

resources/views/registry/_form.blade.php
<div class="col-md-12 text-center" id="form">
  {{-- espacio top y alerta de success --}}
  <div class="top-form">
    @if(session()->has('message'))
      <div id="alert-success">
        {{ session()->get('message') }}
      </div>
    @endif
  </div>


  {{-- formulario --}}
<form method="post" action={{ route('participantes.store')}}  enctype="multipart/form-data" autocomplete="off" >
  @csrf
  <div class="inputs">
    <small class="errors">{{ $errors->first('name', ':message') }}</small>
    <input type="text" name="name" placeholder="NOMBRE" value="{{ old('name') }}" class="{{ $errors->has('name') ? 'is-danger' : '' }}" maxlength="30" required>
  </div>

  <div class="inputs">
    <small class="errors">{{ $errors->first('apellidos', ':message') }}</small>
    <input type="text" name="apellidos" placeholder="APELLIDOS" value="{{ old('apellidos') }}" class="{{ $errors->has('apellidos') ? 'is-danger' : '' }}" maxlength="40" required>
  </div>

  <div class="inputs">
    <small class="errors">{{ $errors->first('dni', ':message') }}</small>
    <input type="text" name="dni" placeholder="NO DE DNI" value="{{ old('dni') }}" class="{{ $errors->has('dni') ? 'is-danger' : '' }}" maxlength="9" required>
  </div>

  <div class="inputs">
    <small class="errors">{{ $errors->first('email', ':message') }}</small>
    <input type="email" name="email" placeholder="EMAIL" value="{{ old('email') }}" class="{{ $errors->has('email') ? 'is-danger' : '' }}" maxlength="50" required>
  </div>

  <div class="inputs">
    <small class="errors">{{ $errors->first('phone', ':message') }}</small>
    <input type="tel" name="phone" placeholder="TELÉFONO" value="{{ old('phone') }}" class="{{ $errors->has('phone') ? 'is-danger' : '' }}"  maxlength="9" required>
  </div>

  <span>Fotos de la entrada</span>

  <div class="files">
    <small class="errors">{{ $errors->first('imgFront', ':message') }}</small>
    <input type="file" id="imgFront" name="imgFront" accept="image/*, application/pdf" data-value="p1" required>
    <label class="{{ $errors->has('imgFront') ? 'is-danger-img' : '' }}" for="imgFront">
      <p id="text_p1">cara frontal</p>
    </label>
  </div>

  <div class="files">
    <small class="errors">{{ $errors->first('imgBack', ':message') }}</small>
    <input type="file" id="imgBack" name="imgBack" accept="image/*, application/pdf" data-value="p2">
    <label class="{{ $errors->has('imgBack') ? 'is-danger-img' : '' }}" for="imgBack">
      <p id="text_p2">cara trasera</p>
    </label>
  </div>

  <button type="submit" class="btn btn-primary">ENVIAR</button>


</form>

</div>

resources/views/registry/index.blade.php
@extends('layouts.default')
@section('content')
  <div class="container text-center" id="registry">

    @include('shared._header')

    @include('shared._date')

    @include('registry._form')

    @include('shared._footer')

  </div>


@endsection

resources/views/shared/_date.blade.php
<div class="col-md-12" id="date_info">
  <div class="date">
    {{-- contador descripcion --}}
    <div class="col-md-6">
      <div class="date_description">
        @if ($pre)
          <span>Inicio del registro</span>
          <span>01 DE MARZO</span>
          <span>12:00 AM España</span>
        @else
          <span>Cierre del registro</span>
          <span>04 DE MARZO</span>
          <span>11:59 PM España</span>
        @endif
      </div>
    </div>

    {{-- contador --}}
    <div class="col-md-6">
      <div class="date_counter">
        <span class="faltan">faltan...</span>
        <div id="clock">
        </div>
      </div>
    </div>
  </div>

</div>

resources/views/shared/_footer.blade.php
<div id="footerGen" class="col-md-12">
  <p>*Sólo se puede participar 1 vez por DNI</p>
  <a href="{{ asset('terminos_condiciones/terminos.pdf') }}" target="_blank">Términos y condiciones</a>
  <p><img src="{{ asset('images/4latas-carro2.png') }}" alt=""></p>
</div>

resources/views/shared/_header.blade.php
<div id="header">
    <div>
      <h3>participa para ganar el coche de</h3>
      <img src="{{ asset('images/4latas-titulo.png') }}" alt="4 LATAS">
      <h4>Una Película de GERARDO OLIVARES</h4>
    </div>
</div>

resources/views/shared/_preloader.blade.php
<div id="preloader">
  <div id="loader"></div>
  <div class="loader-section"></div>
</div>

resources/views/snippets/analytics.blade.php
{{-- <script>
  (function(C,i,r,c,u,s){C.GoogleAnalyticsObject=c;C[c]||(C[c]=
  function(){(C[c].q=C[c].q||[]).push(arguments)});C[c].c=+new Date;
  u=i.createElement(r);s=i.getElementsByTagName(r)[0];
  u.src='https://www.google-analytics.com/analytics.js';
  s.parentNode.insertBefore(u,s)}(window,document,'script','ga'));
  ga('create','UA-XXXXX-X','auto');ga('send','pageview');
</script> --}}

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-135010833-1"></script>

<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-135010833-1');
</script>

resources/views/snippets/favicons.blade.php
<link rel="apple-touch-icon" sizes="180x180" href="{{ asset("images/favicons/apple-icon.png")}}">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="4 LATAS">
<link rel="manifest" href="{{ asset("images/favicons/manifest.json")}}">
<meta name="mobile-web-app-capable" content="yes">
<meta name="theme-color" content="#060856">
<meta name="application-name" content="4 LATAS">
<meta name="msapplication-TileColor" content="#060856">
<meta name="msapplication-TileImage" content="{{ asset("images/favicons/ms-icon-150x150.png")}}">
<meta name="msapplication-config" content="{{ asset("images/favicons/browserconfig.xml")}}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ asset("images/favicons/favicon-32x32.png")}}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ asset("images/favicons/favicon-16x16.png")}}">
<link rel="shortcut icon" href="{{ asset("images/favicons/favicon.ico")}}">

resources/views/snippets/metatags.blade.php
<?php
	$image = asset("images/4latas-fb.png");
	$title = "Participa para ganar el coche de 4 Latas.";
  $description = "Una Película de Gerardo Olivares.";
?>

<meta name="title" content="{{ $title }}"/>
<meta name="author" content="@Netflix"/>
<meta name="description" content="{{ $description }}"/>
<meta property="og:url" content=""/>
<meta property="og:locale" content="en_US"/>
<meta property="og:type" content="website"/>
<meta property="og:title" content="{{ $title }}"/>
<meta property="og:description" content="{{ $description }}"/>
<meta property="og:image" content="{{ $image }}"/>
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:site" content="@Netflix"/>
<meta name="twitter:creator" content="@Netflix"/>
<meta name="twitter:title" content="{{ $title }}"/>
<meta name="twitter:description" content="{{ $description }}"/>
<meta name="twitter:image" content="{{ $image }}"/>

resources/views/snippets/tag_manager.blade.php
{{-- Google Tag Manager (noscript) --}}
<noscript>
  <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XXXXXXX" height="0" width="0" style="display:none;visibility:hidden"></iframe>
</noscript>
{{-- End Google Tag Manager (noscript) --}}